togglz:
  enabled: true # Enable Togglz for the application.
  console:
    enabled: true # Enable admin console.
    path: /togglz-console # The path of the admin console when enabled.
    feature-admin-authority: ROLE_ADMIN # The name of the authority that is allowed to access the admin console.
    secured: false # Indicates if the admin console runs in secured mode. If false the application itself should take care of securing the admin console.
    use-management-port: false # Indicates if the admin console runs on the management port. If no management port is configured it will run on the application port. If set to true the console path will also be prefixed with the management.context-path.